// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lrysfjpospcnkpdcbvdg.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxyeXNmanBvc3BjbmtwZGNidmRnIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM4NTY0MzIsImV4cCI6MjA2OTQzMjQzMn0.ALtHXQjlvgeczNvAOtO5hALFJHES2pjvfxqYXlVrlg0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});